name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features
    - name: Run tests
      run: cargo test --verbose
    - name: wasm-pack-action
      uses: jetli/wasm-pack-action@v0.4.0
    - name: Build Wasm
      run: wasm-pack build
      working-directory: ./s2s_web