name: Release Build

on:
  release:
    types:
      - published

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Cache Cargo modules
        id: cache-cargo
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Build
        run: cargo build --release --verbose --package s2s_cli
      - name: Create Tarball
        if: ${{ matrix.os != 'windows-latest' }}
        run: tar -czvf structure2schematic-${{ matrix.os }}.tar.gz -C target/release s2s_cli
      - name: upload linux/darwin artifact
        if: ${{ matrix.os != 'windows-latest' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url && github.action == 'release' }}
          asset_path: structure2schematic-${{ matrix.os }}.tar.gz
          asset_name: structure2schematic-${{ matrix.os }}.tar.gz
          asset_content_type: application/gzip
      - uses: vimtor/action-zip@v1
        name: Compress
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          files: target/release/s2s_cli.exe
          dest: structure2schematic-${{ matrix.os }}.zip
      - name: upload windows artifact
        if: ${{ matrix.os == 'windows-latest' && github.action == 'release' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: structure2schematic-${{ matrix.os }}.zip
          asset_name: structure2schematic-${{ matrix.os }}.zip
          asset_content_type: application/zip